<?php
$mbpro_border_styles = array(
	'' => '',
	'dashed' => 'dashed',
	'dotted' => 'dotted',
	'double' => 'double',
	'solid' => 'solid'
);

$mbpro_container_alignments = array(
	'' => '',
	'display: inline-block' => 'display: inline-block',
	'float: left' => 'float: left',
	'float: right' => 'float: right'
);

$mbpro_font_families = array(
	'' => '',
	'Arial' => 'Arial',
	'Georgia' => 'Georgia',
	'Tahoma' => 'Tahoma',
	'Times New Roman' => 'Times New Roman',
	'Trebuchet MS' => 'Trebuchet MS',
	'Verdana' => 'Verdana',
	'Aclonica (Google Web Font)' => 'Aclonica',
	'Aldrich (Google Web Font)' => 'Aldrich',
	'Antic Slab (Google Web Font)' => 'Antic Slab',
	'Anton (Google Web Font)' => 'Anton',
	'Arvo (Google Web Font)' => 'Arvo',
	'Asap (Google Web Font)' => 'Asap',
	'Bevan (Google Web Font)' => 'Bevan',
	'Bigelow Rules (Google Web Font)' => 'Bigelow Rules',
	'Bitter (Google Web Font)' => 'Bitter',
	'Cabin (Google Web Font)' => 'Cabin',
	'Candal (Google Web Font)' => 'Candal',
	'Cantarell (Google Web Font)' => 'Cantarell',
	'Changa One (Google Web Font)' => 'Changa One',
	'Cherry Cream Soda (Google Web Font)' => 'Cherry Cream Soda',
	'Cherry Swash (Google Web Font)' => 'Cherry Swash',
	'Copse (Google Web Font)' => 'Copse',
	'Courgette (Google Web Font)' => 'Courgette',
	'Coustard (Google Web Font)' => 'Coustard',
	'Crafty Girls (Google Web Font)' => 'Crafty Girls',
	'Cuprum (Google Web Font)' => 'Cuprum',
	'Dancing Script (Google Web Font)' => 'Dancing Script',
	'Devonshire (Google Web Font)' => 'Devonshire',
	'Dosis (Google Web Font)' => 'Dosis', 
	'Droid Sans (Google Web Font)' => 'Droid Sans',
	'Droid Sans Mono (Google Web Font)' => 'Droid Sans Mono',
	'Droid Serif (Google Web Font)' => 'Droid Serif',
	'EB Garamond (Google Web Font)' => 'EB Garamond',
	'Economica (Google Web Font)' => 'Economica',
	'Electrolize (Google Web Font)' => 'Electrolize',
	'Exo (Google Web Font)' => 'Exo',
	'Francois One (Google Web Font)' => 'Francois One',
	'Grand Hotel (Google Web Font)' => 'Grand Hotel',
	'Gudea (Google Web Font)' => 'Gudea',
	'Josefin Slab (Google Web Font)' => 'Josefin Slab',
	'Karla (Google Web Font)' => 'Karla',
	'Krona One (Google Web Font)' => 'Krona One',
	'Lato (Google Web Font)' => 'Lato',
	'Lily Script One (Google Web Font)' => 'Lily Script One',
	'Lobster (Google Web Font)' => 'Lobster',
	'Lobster Two (Google Web Font)' => 'Lobster Two',
	'Lora (Google Web Font)' => 'Lora',
	'Luckiest Guy (Google Web Font)' => 'Luckiest Guy',
	'Michroma (Google Web Font)' => 'Michroma',
	'Montserrat (Google Web Font)' => 'Montserrat',
	'Noto Sans (Google Web Font)' => 'Noto Sans',
	'Nunito (Google Web Font)' => 'Nunito',
	'Open Sans (Google Web Font)' => 'Open Sans',
	'Open Sans Condensed (Google Web Font)' => 'Open Sans Condensed',
	'Orbitron (Google Web Font)' => 'Orbitron',
	'Oswald (Google Web Font)' => 'Oswald',
	'Pacifico (Google Web Font)' => 'Pacifico',
	'Paytone One (Google Web Font)' => 'Paytone One',
	'PT Sans (Google Web Font)' => 'PT Sans',
	'PT Sans Narrow (Google Web Font)' => 'PT Sans Narrow',
	'Questrial (Google Web Font)' => 'Questrial',
	'Quicksand (Google Web Font)' => 'Quicksand',
	'Rokkitt (Google Web Font)' => 'Rokkitt',
	'Shadows Into Light (Google Web Font)' => 'Shadows Into Light',
	'Source Sans Pro (Google Web Font)' => 'Source Sans Pro',
	'Special Elite (Google Web Font)' => 'Special Elite',
	'Spinnaker (Google Web Font)' => 'Spinnaker',
	'Tangerine (Google Web Font)' => 'Tangerine',
	'Ubuntu (Google Web Font)' => 'Ubuntu',
	'Ubuntu Condensed (Google Web Font)' => 'Ubuntu Condensed',
	'Yanone Kaffeesatz (Google Web Font)' => 'Yanone Kaffeesatz'
);

$mbpro_font_sizes = array(
	'' => '',
	'10px' => '10px',
	'11px' => '11px',
	'12px' => '12px',
	'13px' => '13px',
	'14px' => '14px',
	'15px' => '15px',
	'16px' => '16px',
	'17px' => '17px',
	'18px' => '18px',
	'19px' => '19px',
	'20px' => '20px',
	'21px' => '21px',
	'22px' => '22px',
	'23px' => '23px',
	'24px' => '24px',
	'25px' => '25px',
	'26px' => '26px',
	'27px' => '27px',
	'28px' => '28px',
	'29px' => '29px',
	'30px' => '30px',
	'31px' => '31px',
	'32px' => '32px',
	'33px' => '33px',
	'34px' => '34px',
	'35px' => '35px',
	'36px' => '36px',
	'37px' => '37px',
	'38px' => '38px',
	'39px' => '39px',
	'40px' => '40px',
	'41px' => '41px',
	'42px' => '42px',
	'43px' => '43px',
	'44px' => '44px',
	'45px' => '45px',
	'46px' => '46px',
	'47px' => '47px',
	'48px' => '48px',
	'49px' => '49px',
	'50px' => '50px'
);

$mbpro_font_styles = array(
	'' => '',
	'normal' => 'normal',
	'italic' => 'italic'
);

$mbpro_font_weights = array(
	'' => '',
	'normal' => 'normal',
	'bold' => 'bold'
);

$mbpro_icon_positions = array(
	'' => '',
	'Left of text' => 'left',
	'Right of text' => 'right',
	'Top of text' => 'top',
	'Bottom of text' => 'bottom'
);

$mbpro_text_alignments = array(
	'' => '',
	'left' => 'left',
	'center' => 'center',
	'right' => 'right'
);

$mbpro_icon_array = array(
    'fa-glass',
    'fa-music',
    'fa-search',
    'fa-envelope-o',
    'fa-heart',
    'fa-star',
    'fa-star-o',
    'fa-user',
    'fa-film',
    'fa-th-large',
    'fa-th',
    'fa-th-list',
    'fa-check',
    'fa-times',
    'fa-search-plus',
    'fa-search-minus',
    'fa-power-off',
    'fa-signal',
    'fa-cog',
    'fa-trash-o',
    'fa-home',
    'fa-file-o',
    'fa-clock-o',
    'fa-road',
    'fa-download',
    'fa-arrow-circle-o-down',
    'fa-arrow-circle-o-up',
    'fa-inbox',
    'fa-play-circle-o',
    'fa-repeat',
    'fa-refresh',
    'fa-list-alt',
    'fa-lock',
    'fa-flag',
    'fa-headphones',
    'fa-volume-off',
    'fa-volume-down',
    'fa-volume-up',
    'fa-qrcode',
    'fa-barcode',
    'fa-tag',
    'fa-tags',
    'fa-book',
    'fa-bookmark',
    'fa-print',
    'fa-camera',
    'fa-font',
    'fa-bold',
    'fa-italic',
    'fa-text-height',
    'fa-text-width',
    'fa-align-left',
    'fa-align-center',
    'fa-align-right',
    'fa-align-justify',
    'fa-list',
    'fa-outdent',
    'fa-indent',
    'fa-video-camera',
    'fa-picture-o',
    'fa-pencil',
    'fa-map-marker',
    'fa-adjust',
    'fa-tint',
    'fa-pencil-square-o',
    'fa-share-square-o',
    'fa-check-square-o',
    'fa-arrows',
    'fa-step-backward',
    'fa-fast-backward',
    'fa-backward',
    'fa-play',
    'fa-pause',
    'fa-stop',
    'fa-forward',
    'fa-fast-forward',
    'fa-step-forward',
    'fa-eject',
    'fa-chevron-left',
    'fa-chevron-right',
    'fa-plus-circle',
    'fa-minus-circle',
    'fa-times-circle',
    'fa-check-circle',
    'fa-question-circle',
    'fa-info-circle',
    'fa-crosshairs',
    'fa-times-circle-o',
    'fa-check-circle-o',
    'fa-ban',
    'fa-arrow-left',
    'fa-arrow-right',
    'fa-arrow-up',
    'fa-arrow-down',
    'fa-share',
    'fa-expand',
    'fa-compress',
    'fa-plus',
    'fa-minus',
    'fa-asterisk',
    'fa-exclamation-circle',
    'fa-gift',
    'fa-leaf',
    'fa-fire',
    'fa-eye',
    'fa-eye-slash',
    'fa-exclamation-triangle',
    'fa-plane',
    'fa-calendar',
    'fa-random',
    'fa-comment',
    'fa-magnet',
    'fa-chevron-up',
    'fa-chevron-down',
    'fa-retweet',
    'fa-shopping-cart',
    'fa-folder',
    'fa-folder-open',
    'fa-arrows-v',
    'fa-arrows-h',
    'fa-bar-chart-o',
    'fa-twitter-square',
    'fa-facebook-square',
    'fa-camera-retro',
    'fa-key',
    'fa-cogs',
    'fa-comments',
    'fa-thumbs-o-up',
    'fa-thumbs-o-down',
    'fa-star-half',
    'fa-heart-o',
    'fa-sign-out',
    'fa-linkedin-square',
    'fa-thumb-tack',
    'fa-external-link',
    'fa-sign-in',
    'fa-trophy',
    'fa-github-square',
    'fa-upload',
    'fa-lemon-o',
    'fa-phone',
    'fa-square-o',
    'fa-bookmark-o',
    'fa-phone-square',
    'fa-twitter',
    'fa-facebook',
    'fa-github',
    'fa-unlock',
    'fa-credit-card',
    'fa-rss',
    'fa-hdd-o',
    'fa-bullhorn',
    'fa-bell',
    'fa-certificate',
    'fa-hand-o-right',
    'fa-hand-o-left',
    'fa-hand-o-up',
    'fa-hand-o-down',
    'fa-arrow-circle-left',
    'fa-arrow-circle-right',
    'fa-arrow-circle-up',
    'fa-arrow-circle-down',
    'fa-globe',
    'fa-wrench',
    'fa-tasks',
    'fa-filter',
    'fa-briefcase',
    'fa-arrows-alt',
    'fa-users',
    'fa-link',
    'fa-cloud',
    'fa-flask',
    'fa-scissors',
    'fa-files-o',
    'fa-paperclip',
    'fa-floppy-o',
    'fa-square',
    'fa-bars',
    'fa-list-ul',
    'fa-list-ol',
    'fa-strikethrough',
    'fa-underline',
    'fa-table',
    'fa-magic',
    'fa-truck',
    'fa-pinterest',
    'fa-pinterest-square',
    'fa-google-plus-square',
    'fa-google-plus',
    'fa-money',
    'fa-caret-down',
    'fa-caret-up',
    'fa-caret-left',
    'fa-caret-right',
    'fa-columns',
    'fa-sort',
    'fa-sort-desc',
    'fa-sort-asc',
    'fa-envelope',
    'fa-linkedin',
    'fa-undo',
    'fa-gavel',
    'fa-tachometer',
    'fa-comment-o',
    'fa-comments-o',
    'fa-bolt',
    'fa-sitemap',
    'fa-umbrella',
    'fa-clipboard',
    'fa-lightbulb-o',
    'fa-exchange',
    'fa-cloud-download',
    'fa-cloud-upload',
    'fa-user-md',
    'fa-stethoscope',
    'fa-suitcase',
    'fa-bell-o',
    'fa-coffee',
    'fa-cutlery',
    'fa-file-text-o',
    'fa-building-o',
    'fa-hospital-o',
    'fa-ambulance',
    'fa-medkit',
    'fa-fighter-jet',
    'fa-beer',
    'fa-h-square',
    'fa-plus-square',
    'fa-angle-double-left',
    'fa-angle-double-right',
    'fa-angle-double-up',
    'fa-angle-double-down',
    'fa-angle-left',
    'fa-angle-right',
    'fa-angle-up',
    'fa-angle-down',
    'fa-desktop',
    'fa-laptop',
    'fa-tablet',
    'fa-mobile',
    'fa-circle-o',
    'fa-quote-left',
    'fa-quote-right',
    'fa-spinner',
    'fa-circle',
    'fa-reply',
    'fa-github-alt',
    'fa-folder-o',
    'fa-folder-open-o',
    'fa-smile-o',
    'fa-frown-o',
    'fa-meh-o',
    'fa-gamepad',
    'fa-keyboard-o',
    'fa-flag-o',
    'fa-flag-checkered',
    'fa-terminal',
    'fa-code',
    'fa-reply-all',
    'fa-star-half-o',
    'fa-location-arrow',
    'fa-crop',
    'fa-code-fork',
    'fa-chain-broken',
    'fa-question',
    'fa-info',
    'fa-exclamation',
    'fa-superscript',
    'fa-subscript',
    'fa-eraser',
    'fa-puzzle-piece',
    'fa-microphone',
    'fa-microphone-slash',
    'fa-shield',
    'fa-calendar-o',
    'fa-fire-extinguisher',
    'fa-rocket',
    'fa-maxcdn',
    'fa-chevron-circle-left',
    'fa-chevron-circle-right',
    'fa-chevron-circle-up',
    'fa-chevron-circle-down',
    'fa-html5',
    'fa-css3',
    'fa-anchor',
    'fa-unlock-alt',
    'fa-bullseye',
    'fa-ellipsis-h',
    'fa-ellipsis-v',
    'fa-rss-square',
    'fa-play-circle',
    'fa-ticket',
    'fa-minus-square',
    'fa-minus-square-o',
    'fa-level-up',
    'fa-level-down',
    'fa-check-square',
    'fa-pencil-square',
    'fa-external-link-square',
    'fa-share-square',
    'fa-compass',
    'fa-caret-square-o-down',
    'fa-caret-square-o-up',
    'fa-caret-square-o-right',
    'fa-eur',
    'fa-gbp',
    'fa-usd',
    'fa-inr',
    'fa-jpy',
    'fa-rub',
    'fa-krw',
    'fa-btc',
    'fa-file',
    'fa-file-text',
    'fa-sort-alpha-asc',
    'fa-sort-alpha-desc',
    'fa-sort-amount-asc',
    'fa-sort-amount-desc',
    'fa-sort-numeric-asc',
    'fa-sort-numeric-desc',
    'fa-thumbs-up',
    'fa-thumbs-down',
    'fa-youtube-square',
    'fa-youtube',
    'fa-xing',
    'fa-xing-square',
    'fa-youtube-play',
    'fa-dropbox',
    'fa-stack-overflow',
    'fa-instagram',
    'fa-flickr',
    'fa-adn',
    'fa-bitbucket',
    'fa-bitbucket-square',
    'fa-tumblr',
    'fa-tumblr-square',
    'fa-long-arrow-down',
    'fa-long-arrow-up',
    'fa-long-arrow-left',
    'fa-long-arrow-right',
    'fa-apple',
    'fa-windows',
    'fa-android',
    'fa-linux',
    'fa-dribbble',
    'fa-skype',
    'fa-foursquare',
    'fa-trello',
    'fa-female',
    'fa-male',
    'fa-gittip',
    'fa-sun-o',
    'fa-moon-o',
    'fa-archive',
    'fa-bug',
    'fa-vk',
    'fa-weibo',
    'fa-renren',
    'fa-pagelines',
    'fa-stack-exchange',
    'fa-arrow-circle-o-right',
    'fa-arrow-circle-o-left',
    'fa-caret-square-o-left',
    'fa-dot-circle-o',
    'fa-wheelchair',
    'fa-vimeo-square',
    'fa-try',
    'fa-plus-square-o',
    'fa-space-shuttle',
    'fa-slack',
    'fa-envelope-square',
    'fa-wordpress',
    'fa-openid',
    'fa-university',
    'fa-graduation-cap',
    'fa-yahoo',
    'fa-google',
    'fa-reddit',
    'fa-reddit-square',
    'fa-stumbleupon-circle',
    'fa-stumbleupon',
    'fa-delicious',
    'fa-digg',
    'fa-pied-piper',
    'fa-pied-piper-alt',
    'fa-drupal',
    'fa-joomla',
    'fa-language',
    'fa-fax',
    'fa-building',
    'fa-child',
    'fa-paw',
    'fa-spoon',
    'fa-cube',
    'fa-cubes',
    'fa-behance',
    'fa-behance-square',
    'fa-steam',
    'fa-steam-square',
    'fa-recycle',
    'fa-car',
    'fa-taxi',
    'fa-tree',
    'fa-spotify',
    'fa-deviantart',
    'fa-soundcloud',
    'fa-database',
    'fa-file-pdf-o',
    'fa-file-word-o',
    'fa-file-excel-o',
    'fa-file-powerpoint-o',
    'fa-file-image-o',
    'fa-file-archive-o',
    'fa-file-audio-o',
    'fa-file-video-o',
    'fa-file-code-o',
    'fa-vine',
    'fa-codepen',
    'fa-jsfiddle',
    'fa-life-ring',
    'fa-circle-o-notch',
    'fa-rebel',
    'fa-empire',
    'fa-git-square',
    'fa-git',
    'fa-hacker-news',
    'fa-tencent-weibo',
    'fa-qq',
    'fa-weixin',
    'fa-paper-plane',
    'fa-paper-plane-o',
    'fa-history',
    'fa-circle-thin',
    'fa-header',
    'fa-paragraph',
    'fa-sliders',
    'fa-share-alt',
    'fa-share-alt-square',
    'fa-bomb',
    'fa-angellist',
    'fa-area-chart',
    'fa-at',
    'fa-bell-slash',
    'fa-bell-slash-o',
    'fa-bicycle',
    'fa-binoculars',
    'fa-birthday-cake',
    'fa-bus',
    'fa-calculator',
    'fa-cc',
    'fa-cc-amex',
    'fa-cc-discover',
    'fa-cc-mastercard',
    'fa-cc-paypal',
    'fa-cc-stripe',
    'fa-cc-visa',
    'fa-copyright',
    'fa-eyedropper',
    'fa-futbol-o',
    'fa-google-wallet',
    'fa-ils',
    'fa-ioxhost',
    'fa-lastfm',
    'fa-lastfm-square',
    'fa-line-chart',
    'fa-meanpath',
    'fa-newspaper-o',
    'fa-paint-brush',
    'fa-paypal',
    'fa-pie-chart',
    'fa-plug',
    'fa-shekel', 
    'fa-sheqel',
    'fa-slideshare',
    'fa-soccer-ball-o',
    'fa-toggle-off',
    'fa-toggle-on',
    'fa-trash',
    'fa-tty',
    'fa-twitch',
    'fa-wifi',
    'fa-yelp',

);


?>
