<?php
/**
 * Default template for displaying the user
 * registration page.
 *
 * @since   1.0
 * @version 1.0
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/content-registration.php
 */
?>
<?php if ( itegfp_override_registration() ): ?>
	<script type="text/javascript">
		jQuery(document).bind('gform_confirmation_loaded', function (event, form_id) {
			window.location.href = "<?php echo it_exchange_get_page_url('account'); ?>";
		});
	</script>
<?php endif; ?>

<?php do_action( 'it_exchange_content_registration_before_wrap' ); ?>
<div id="it-exchange-registration" class="it-exchange-wrap it-exchange-account">
	<?php do_action( 'it_exchange_content_registration_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<?php if ( is_user_logged_in() ) : ?>
		<?php it_exchange_get_template_part( 'content-registration/elements/user-logged-in' ); ?>
	<?php else : ?>
		<?php if ( it_exchange( 'registration', 'is-enabled' ) ) : ?>
			<?php do_action( 'it_exchange_content_registration_before_form' ); ?>

			<?php if ( itegfp_override_registration() ): ?>
				<?php gravity_form( itegfp_override_registration(), true, true, false, null, true ); ?>
			<?php endif; ?>

			<?php it_exchange( 'registration', 'form-open' ); ?>

			<?php if ( itegfp_override_registration() ): ?>
				<?php it_exchange_get_template_part( 'content-registration/elements/login' ); ?>
			<?php else: ?>
				<?php it_exchange_get_template_part( 'content-registration/loops/fields' ); ?>
				<?php it_exchange_get_template_part( 'content-registration/loops/actions' ); ?>
			<?php endif; ?>

			<?php it_exchange( 'registration', 'form-close' ); ?>
			<?php do_action( 'it_exchange_content_registration_after_form' ); ?>
		<?php else : ?>
			<?php it_exchange_get_template_part( 'content-registration/elements/registration-disabled-message' ); ?>
		<?php endif; ?>
	<?php endif; ?>
	<?php do_action( 'it_exchange_content_registration_end_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_registration_after_wrap' ); ?>
